### ISSUE TITLE
There is not Email icon in SVG folder

### ISSUE THREAD

**Issue by tal007** [framework7io/framework7-icons#23]
Where i use f7-icons, add class email and email-fill, but it's not work

![image](https://user-images.githubusercontent.com/25813059/70775523-4b221680-1db6-11ea-8062-c52b5918d30a.png)
![image](https://user-images.githubusercontent.com/25813059/70775550-4f4e3400-1db6-11ea-82c6-940fa5f56bb2.png)

**Comment by shastox** [comment]
https://framework7.io/icons/

**Comment by nolimits4web** [comment]
There us no email_fill icon
